using System;
using Newtonsoft.Json;

namespace TaleSpireMapGen.Generation
{
    public class AiTemplate : ITemplate
    {
        public string Name => "AI";
        public string Description => "Paste a JSON layout spec generated by an AI agent";

        public LayoutSpec Generate(TemplateParams parameters)
        {
            if (string.IsNullOrWhiteSpace(parameters.AiJson))
                throw new InvalidOperationException("AI template requires a JSON layout spec in TemplateParams.AiJson.");

            LayoutSpec spec;
            try
            {
                spec = JsonConvert.DeserializeObject<LayoutSpec>(parameters.AiJson);
            }
            catch (JsonException ex)
            {
                throw new InvalidOperationException($"Failed to parse AI JSON as LayoutSpec: {ex.Message}", ex);
            }

            if (spec == null)
                throw new InvalidOperationException("AI JSON deserialized to null — check that the input is a valid LayoutSpec object.");

            if (spec.Rooms == null || spec.Rooms.Count == 0)
                throw new InvalidOperationException("LayoutSpec must contain at least one room.");

            return spec;
        }
    }
}
